from __future__ import print_function


ELUA_TNIL     = 0
ELUA_TBOOLEAN = 1
ELUA_TROTABLE = 2
ELUA_TLIGHTFUNCTION = 3
ELUA_TLIGHTUSERDATA	= 4
ELUA_TNUMBER = 5
ELUA_TSTRING = 6
ELUA_TTABLE  = 7
ELUA_TFUNCTION = 8
ELUA_TUSERDATA = 9
ELUA_TTHREAD   = 10

